### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [KelkooGroup/sales-tracking-gtm-template#1]
Thank you for submitting template to the gallery. However, there were a few issues that needs to be resolved ahead of approving the template for the gallery.

1. The url [](https://www.kelkoogroup.com/kelkoo-customer-service/support-for-merchants/sales-tracking-guides/google-tag-manager) mentioned in the template description shows "Page not found" error. Please resolve the issue.
2. User instructions to install the template should direct users to install the gallery version of the template by clicking on the "Search Gallery" button in the template tab to add the gallery template. Instead it was mentioned to install template directly from github repository. Please update the instructions accordingly.
3. data.gtmOnSuccess(); and data.gtmOnFailure(); functions are called well in advance in the script. Please update the code accordingly

**Comment by notflorian** [comment]
Hello @praveena-pappu,

Thanks for your review, I took into account your comments in https://github.com/KelkooGroup/sales-tracking-gtm-template/commit/aa5604a0e7e04bc7195ee43bf0aecc1fa3b16872

Do I need to submit again the template to the gallery?

**Comment by notflorian** [comment]
Hello @praveena-pappu,

Any chance you will have some time soon to approve our GTM template?

Thanks

**Comment by philpott** [comment]
Your template has been reviewed and will be showing up in the gallery soon.
